// Word bank with 30 simple words and their visual emojis
export const WORDS = [
  { word: 'CAT', emoji: '🐱' },
  { word: 'DOG', emoji: '🐕' },
  { word: 'SUN', emoji: '☀️' },
  { word: 'CAR', emoji: '🚗' },
  { word: 'BUS', emoji: '🚌' },
  { word: 'HAT', emoji: '🎩' },
  { word: 'CUP', emoji: '☕' },
  { word: 'PEN', emoji: '✒️' },
  { word: 'BEE', emoji: '🐝' },
  { word: 'KEY', emoji: '🔑' },
  { word: 'BAT', emoji: '🦇' },
  { word: 'PIE', emoji: '🥧' },
  { word: 'EGG', emoji: '🥚' },
  { word: 'FOX', emoji: '🦊' },
  { word: 'BAG', emoji: '👜' },
  { word: 'BOX', emoji: '📦' },
  { word: 'FAN', emoji: '🪭' },
  { word: 'BED', emoji: '🛏️' },
  { word: 'ICE', emoji: '🧊' },
  { word: 'ANT', emoji: '🐜' },
  { word: 'OWL', emoji: '🦉' },
  { word: 'JAR', emoji: '🫙' },
  { word: 'NET', emoji: '🥅' },
  { word: 'MAP', emoji: '🗺️' },
  { word: 'PIG', emoji: '🐷' },
  { word: 'COW', emoji: '🐮' },
  { word: 'APE', emoji: '🦍' },
  { word: 'BAT', emoji: '⚾' },
  { word: 'BOW', emoji: '🎀' },
  { word: 'GEM', emoji: '💎' }
];
